### ISSUE TITLE
The definition of Status will result in undefined behavior

### ISSUE THREAD

**Issue by retep998** [pravic/winapi-kmd-rs#1]
If a function returns any value for `Status` other than the variants you have defined, it will result in undefined behavior. This is one of the big reasons I moved _away_ from Rust enums for winapi.

**Comment by pravic** [comment]
Thanks for mention. It is not a problem to declare rest of NTSTATUS constants, I just skipped it during porting. And I really don't like the old C constants, so I use `enum` wherever it possible.

Also I will be very grateful if you tell me an idiomatic way (even in RFC state) to handle C enums.

**Comment by retep998** [comment]
Using integer constants _is_ the idiomatic way to handle integer constants and C enums when doing FFI. You'd then use a Rust enum for the safe Rusty API you expose to downstream Rust consumers where you'd safely convert between integers to/from C and the Rust enums to/from downstream Rust crates.

**Comment by pravic** [comment]
What purpose on repr(C) for enums then?

**Comment by retep998** [comment]
To be useless. https://github.com/rust-lang/rust/issues/28925 covers some of the issues with `#[repr(C)]` on enums.
