### ISSUE TITLE
Could not find specification for target "i686-sys-windows-msvc"

### ISSUE THREAD

**Issue by petersondrew** [pravic/winapi-kmd-rs#3]
Forgive me if the solution is obvious, I'm still very new to Rust and Cargo, but for some reason when following the steps to build the minimal example in the readme, Cargo is not picking up the targets defined in the .cargo directory pulled in from kmd-env-rs.

Any thoughts on resolving this? Thanks!

**Comment by pravic** [comment]
Either set `RUST_TARGET_PATH=path/to/kmd-env-rs/.cargo/` or run `cargo build --release --target path/to/i686-sys-windows-msvc.json`.

I forgot about this.

**Comment by petersondrew** [comment]
That solved that, thanks
