### ISSUE TITLE
Add notes on where LIBPATH needs to be changed for your local DDK path

### ISSUE THREAD

**Issue by petersondrew** [pravic/winapi-kmd-rs#4]
I've noticed a few places with hard-coded paths to the DDK path and sub-directories (such as the target json files). The readme could use a few notes on which files need to be changed to set that path to your local installation path.

**Comment by pravic** [comment]
Thanks. I was just forgotten in amd64 target, since I use rustc-link-search. 
[Fixed](https://github.com/pravic/kmd-env-rs/commit/2f95940ff43401eea44c1d7f808208f267325b32).

**Comment by pravic** [comment]
> few places

I found only one. Where are the others?

**Comment by petersondrew** [comment]
The build.cmd file for example 3 also includes a hard-coded path to the ddk

**Comment by pravic** [comment]
Fixed too. Anyway, build.cmd may be used just for manual compilation, it comes when dylib compilation was not been supported.

**Comment by petersondrew** [comment]
Awesome, thank you. Really excited about this project :smile:
