### ISSUE TITLE
x86_64 target tries to link to 32 bit msvcrt

### ISSUE THREAD

**Issue by petersondrew** [pravic/winapi-kmd-rs#5]
I've changed my default build target to x86_64-sys-windows-msvc and opted to use the x86_64 nightly rust using rustup, however the target appears to be attempting to link with 32 bit msvcrt:
`note: msvcrt.lib(chkstk.obj) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'`
I can see in my output that it's using the correct version of rustc as well as the x64 msvc toolchain, it's just attempting to link to the wrong version of msvcrt.lib.
Any ideas? Thanks for your help.

**Comment by pravic** [comment]
It seems it used default target.

Try this:

```
03.urandom>cargo clean
03.urandom>cargo build --release --target i686-sys-windows-msvc
03.urandom>cargo build --release --target x86_64-sys-windows-msvc
```

Path to `kmd-env-rs/.cargo` must be in `RUST_TARGET_PATH`.

**Comment by petersondrew** [comment]
Output for x86_64:

```
> echo $env:RUST_TARGET_PATH
C:\code\kmd-env-rs\.cargo\
> rustc --version
rustc 1.9.0-nightly (2b6020723 2016-04-13)
> rustup show
nightly-x86_64-pc-windows-msvc (directory override for '\\?\C:\code\kmd-env-rs')
> cargo build --release --target x86_64-sys-windows-msvc
   Compiling rust.drv.examples.urandom v0.1.0 (file:///C:/code/kmd-env-rs/km/examples/03.urandom)
   Compiling core v0.0.0 (file:///C:/code/kmd-env-rs/libcore)
error: linking with `link.exe` failed: exit code: 1112
note: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\dpeterson\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\code\\kmd-env-rs\\km\\examples\\03.urandom\\target\\release\\build\\core-30cef6f3d5f4b436\\build_script_build.0.o" "/OUT:C:\\code\\kmd-env-rs\\km\\examples\\03.urandom\\target\\release\\build\\core-30cef6f3d5f4b436\\build_script_build.exe" "/OPT:REF,ICF" "/DEBUG" "/LIBPATH:C:\\code\\kmd-env-rs\\km\\examples\\03.urandom\\target\\release\\deps" "/LIBPATH:C:\\code\\kmd-env-rs\\km\\examples\\03.urandom\\target\\release\\deps" "/LIBPATH:C:\\Users\\dpeterson\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\dpeterson\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-18402db3.rlib" "C:\\Users\\dpeterson\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcollections-18402db3.rlib" "C:\\Users\\dpeterson\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_unicode-18402db3.rlib" "C:\\Users\\dpeterson\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librand-18402db3.rlib" "C:\\Users\\dpeterson\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-18402db3.rlib" "C:\\Users\\dpeterson\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-18402db3.rlib" "C:\\Users\\dpeterson\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-18402db3.rlib" "C:\\Users\\dpeterson\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-18402db3.rlib" "ws2_32.lib" "userenv.lib" "shell32.lib" "advapi32.lib" "msvcrt.lib" "compiler-rt.lib"
note: msvcrt.lib(chkstk.obj) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'

error: aborting due to previous error
error: Could not compile `core`.
```

If I switch to i686 with rustup, and run the i686 target, linking works just fine.

**Comment by pravic** [comment]
Looks like it does not use target description. No idea why.
Try to edit .cargo/config and change `i686-sys-windows-msvc` to `x86_64-sys-windows-msvc` as mentioned [here](https://github.com/pravic/winapi-kmd-rs/commit/6d0ffc8e2754363d88bbc30f09ee81d8bd7ab819) - it is in README.md now.

Also, current rustc version is "rustc 1.10.0-nightly (2174bd97c 2016-04-14)", but yesterday it compiled well too.

**Comment by petersondrew** [comment]
I had already done that step - I'm stepping through with ProcMon now to see where Link is loading MSVCRT from.

**Comment by pravic** [comment]
And... ?

**Comment by petersondrew** [comment]
Well it appears to be loading from C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\msvcrt.lib, which is not where it should be loading from, despite the rest of the environment being configured for the x64 msvc toolchain. I'm trying to figure out if this is a situation where the rust compiler is getting tripped up by the environment or what. I'll keep you posted as I'm testing things.

**Comment by pravic** [comment]
Guess, you going by wrong way. The whole command line to link.exe is for common rustc binaries, it completely differs from target.json keys.

**Comment by petersondrew** [comment]
This is definitely something related to my environment, my path is set up for the x64 msvc toolchain but something is not being picked up right - going to close this and dig into the rustc side of it. Thanks.

**Comment by pravic** [comment]
Well.
Though there are 4 ways to specify target:
1. `.cargo/config`
2. `CARGO_BUILD_TARGET`, it is same as above
3. `--target i686-sys-windows-msvc`
4. `--target path/to/i686-sys-windows-msvc.json`, but with this way you need to specify `RUSTFLAGS` with flags and paths taken from _.cargo/config_ manually: 

```
set RUSTFLAGS=-L ..\..\..\native\win7\i386 --cfg disable_float -C soft-float
cargo build --target ..\..\..\.cargo\i686-sys-windows-msvc.json
```

**Comment by mvd4** [comment]
Hi,

just wondering if / how you solved that problem,because I'm having exactly the same today after installing the x64 version.

thx

mvd

**Comment by pravic** [comment]
kmd-rs is broken under current Rust compiler, btw. It needs some time to investigate and make corresponding updates.
